#!/usr/bin/perl

use strict;
use Cwd;
use File::Find::Rule;
use XML::RSS;
use HTML::Entities;
use Data::Dumper;
$Data::Dumper::Terse     = 1;
$Data::Dumper::Indent    = 1;
$Data::Dumper::Useqq     = 1;
$Data::Dumper::Deparse   = 1;
$Data::Dumper::Quotekeys = 0;
$Data::Dumper::Sortkeys  = 1;

my $rss = XML::RSS->new(version => '1.0');

$rss->channel(
  title         => 'japh.se',
  link          => 'http://japh.se',
  description   => 'foobar',

  language      => 'en-us',
);

my @posts = File::Find::Rule->file()
  ->name('*')
  ->in('_genSite/all');


map { s|_genSite/|http://japh.se/| } @posts;
map { s|/index\.html|| } @posts;

print "$_\n" for sort @posts;


for my $post(@posts) {
  $rss->add_item(
    title       => 'foobar',
    link        => "'$post'",
    description => 'foobar',
  );
}

print $rss->as_string;
